name: istanbul-ferries-env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.9.7
  - sqlite
  - numpy
  - pandas
  - matplotlib
  - contextily
  - shapely
  - geopandas
  - notebook
  - pip
  - pip:
    - -e .
    - doit
